[manifest]

id = "salemmm"

version = "1.0.0"

display_name = "Salem - Hero of Time (Majora's Mask)"

description =  """
Salem The Hero of Time Majora's Mask Edition.

Sequel to the Ocarina of Time version: https://gamebanana.com/mods/582473"""

short_description = "Salem - Hero of Time Majora's Mask Edition."

authors = [ "Jameriquiah" ]

game_id = "mm"

minimum_recomp_version = "1.2.2"

dependencies = [
    "yazmt_mm_playermodelmanager"
]

optional_dependencies = [
]

native_libraries = [
]

[inputs]

elf_path = "build/mod.elf"

mod_filename = "salemmm"

func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

additional_files = [ ]

[[manifest.config_options]]
id = "enum_option"
name = "Enum Option"
description = "Test enum config option"
type = "Enum"
options = [ "First", "Second" ]
default = "First"

[[manifest.config_options]]
id = "number_option"
name = "Number Option"
description = "Test number config option."
type = "Number"
min = 0
max = 10
step = 0.1
precision = 1
percent = false
default = 1

[[manifest.config_options]]
id = "string_option"
name = "String Option"
description = "Test string config option."
type = "String"
default = "Lorem Ipsum"
